name: deploy
env:
  PUBLIC_GITHUBUSER: "flicksolutions"
  PUBLIC_GITHUBREPONAME: "skeleton-static"
  PUBLIC_GITHUBBRANCH: "master"
on:
  push:
    branches:
      - main
      - master
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: npm install
      - run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CYON_KEY }}
          known_hosts: undefined

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
